# MySQL DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rideshare
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# Gmail SMTP configuration for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=23r21a05r9@mlrit.ac.in 
spring.mail.password=onsf nytw zwde nmxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Fare configuration (Milestone 2)

fare.bike.base=30
fare.bike.rate=8

fare.auto.base=40
fare.auto.rate=10

fare.car.base=50
fare.car.rate=12

fare.surge.enabled=true
fare.surge.multiplier=1.5

fare.minimum=60

fare.night.enabled=true
fare.night.percentage=20
fare.night.start=22
fare.night.end=5

fare.waiting.enabled=true
fare.waiting.freeMinutes=5
fare.waiting.perMinute=2

razorpay.key.id=rzp_test_SNY0d6qagOQlWy
razorpay.key.secret=XNcTZbJzyq1Em7ayYXiY7ioI

google.maps.api.key=AIzaSyDlEn8BEVomMbyC1blzlQpohKFDPLFYc2Q

# Twilio SMS configuration
twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER