# MySQL DB configuration
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


resend.api.key=${RESEND_API_KEY}

# Fare configuration (Milestone 2)

fare.bike.base=30
fare.bike.rate=8

fare.auto.base=40
fare.auto.rate=10

fare.car.base=50
fare.car.rate=12

fare.surge.enabled=true
fare.surge.multiplier=1.5

fare.minimum=60

fare.night.enabled=true
fare.night.percentage=20
fare.night.start=22
fare.night.end=5

fare.waiting.enabled=true
fare.waiting.freeMinutes=5
fare.waiting.perMinute=2

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

google.maps.api.key=${GOOGLE_MAPS_API_KEY}

# Twilio SMS configuration
twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER 